import React from 'react';
import { TriageResponse } from '../types';
import { 
  AlertTriangle, 
  CheckCircle, 
  Info, 
  Phone, 
  Share2, 
  Utensils, 
  ArrowRight, 
  FileText,
  MessageSquare,
  Printer,
  QrCode
} from 'lucide-react';

interface ResultViewProps {
  result: TriageResponse;
  onReset: () => void;
}

const ResultView: React.FC<ResultViewProps> = ({ result, onReset }) => {
  
  const getTriageColor = (level: string) => {
    switch (level.toLowerCase()) {
      case 'urgent': return 'bg-red-100 border-red-500 text-red-800';
      case 'high': return 'bg-orange-100 border-orange-500 text-orange-800';
      case 'moderate': return 'bg-yellow-100 border-yellow-500 text-yellow-800';
      default: return 'bg-green-100 border-green-500 text-green-800';
    }
  };

  const getTriageIcon = (level: string) => {
    switch (level.toLowerCase()) {
      case 'urgent': return <AlertTriangle className="w-8 h-8 text-red-600" />;
      case 'high': return <AlertTriangle className="w-8 h-8 text-orange-600" />;
      case 'moderate': return <Info className="w-8 h-8 text-yellow-600" />;
      default: return <CheckCircle className="w-8 h-8 text-green-600" />;
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6 pb-24 print:pb-0">
      
      {/* Print Header - Only visible when printing */}
      <div className="hidden print:block mb-6 text-center border-b pb-4">
        <h1 className="text-2xl font-bold">SevaSetu: Clinical Triage Report</h1>
        <p className="text-sm text-gray-500">Generated by AI Clinical Assistant</p>
      </div>

      {/* Top Triage Banner */}
      <div className={`p-6 rounded-xl border-l-8 shadow-sm flex items-start gap-4 ${getTriageColor(result.triage_level)}`}>
        <div className="shrink-0 bg-white p-3 rounded-full shadow-sm">
            {getTriageIcon(result.triage_level)}
        </div>
        <div>
            <div className="uppercase tracking-wide text-sm font-bold opacity-80 mb-1">Triage Category</div>
            <h1 className="text-3xl font-bold capitalize">{result.triage_level} Risk</h1>
            <p className="mt-2 text-xs text-gray-600">Visit ID: {result.visit_id}</p>
        </div>
      </div>

      {/* Condition Summary */}
      <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
        <h2 className="text-xl font-bold text-gray-900 mb-3 flex items-center gap-2">
            <StethoscopeIcon /> Clinical Summary
        </h2>
        <p className="text-gray-700 text-lg leading-relaxed">
            {result.summary_text}
        </p>
      </div>

      <div className="grid md:grid-cols-2 gap-6 print:block print:space-y-6">
        {/* Action Plan */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 break-inside-avoid">
            <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                <CheckCircle className="text-blue-600" /> Recommended Actions
            </h2>
            <ul className="space-y-3">
                {result.action_checklist.map((action, idx) => (
                    <li key={idx} className="flex items-start gap-3 p-3 bg-blue-50 rounded-lg print:bg-transparent print:p-0">
                        <div className="w-6 h-6 bg-blue-600 text-white rounded-full flex items-center justify-center shrink-0 text-sm font-bold print:text-black print:bg-transparent print:border print:border-black">
                            {idx + 1}
                        </div>
                        <span className="text-gray-800 font-medium">{action}</span>
                    </li>
                ))}
            </ul>
        </div>

        {/* Nutrition & Lifestyle */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200 break-inside-avoid">
            <h2 className="text-lg font-bold text-gray-900 mb-4 flex items-center gap-2">
                <AlertTriangle className="text-red-600" /> Emergency Warning Signs
            </h2>
            <ul className="space-y-3">
                {result.emergency_signs.map((sign, idx) => (
                    <li key={idx} className="flex items-start gap-2 text-gray-700">
                        <ArrowRight className="w-5 h-5 text-red-500 shrink-0 mt-0.5" />
                        <span>{sign}</span>
                    </li>
                ))}
            </ul>
        </div>
      </div>

      {/* Risk Scores */}
      {result.risk_scores && (
        <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
          <h2 className="text-xl font-bold text-gray-900 mb-4">Risk Assessment Breakdown</h2>
          <div className="grid grid-cols-2 md:grid-cols-3 gap-4">
            {Object.entries(result.risk_scores).map(([key, value]) => (
              value && (
                <div key={key} className="p-4 bg-gray-50 rounded-lg">
                  <div className="text-sm text-gray-600 capitalize mb-1">{key}</div>
                  <div className="text-2xl font-bold">{value.score || 'N/A'}</div>
                  <div className={`text-xs font-semibold uppercase mt-1 ${
                    value.level === 'high' || value.level === 'urgent' ? 'text-red-600' :
                    value.level === 'moderate' ? 'text-yellow-600' : 'text-green-600'
                  }`}>{value.level || 'unknown'}</div>
                </div>
              )
            ))}
          </div>
        </div>
      )}

      {/* Voice Message - Hide in Print */}
      <div className="space-y-4 print:hidden">
          <h2 className="text-xl font-bold text-gray-900">Communication</h2>
          
          <div className="bg-emerald-50 p-5 rounded-xl border border-emerald-200">
            <div className="flex justify-between items-center mb-2">
                <h3 className="font-bold text-emerald-800 flex items-center gap-2">
                    <MessageSquare className="w-4 h-4" /> Voice Message for Patient
                </h3>
                <button 
                    onClick={() => navigator.clipboard.writeText(result.voice_text).then(() => alert('Copied to clipboard!'))}
                    className="text-xs bg-white border border-emerald-300 px-3 py-1 rounded-full hover:bg-emerald-100 text-emerald-700 font-medium transition-colors"
                >
                    Copy Text
                </button>
            </div>
            <p className="text-emerald-900 italic p-3 bg-white/50 rounded-lg">
                "{result.voice_text}"
            </p>
            <div className="mt-3 flex gap-2">
                 <button className="flex-1 bg-green-500 hover:bg-green-600 text-white py-3 rounded-lg font-bold flex items-center justify-center gap-2 transition-colors shadow-sm">
                    <Share2 className="w-4 h-4" /> WhatsApp Report
                 </button>
                 <button className="flex-1 bg-blue-500 hover:bg-blue-600 text-white py-3 rounded-lg font-bold flex items-center justify-center gap-2 transition-colors shadow-sm">
                    <Phone className="w-4 h-4" /> Send SMS
                 </button>
            </div>
          </div>

          {result.reasons && result.reasons.length > 0 && (
             <div className="bg-slate-50 p-5 rounded-xl border border-slate-200">
                <h3 className="font-bold text-slate-800 flex items-center gap-2 mb-2">
                    <FileText className="w-4 h-4" /> Clinical Reasoning
                </h3>
                <div className="space-y-2">
                  {result.reasons.map((reason, idx) => (
                    <div key={idx} className="bg-white p-3 rounded border border-slate-200">
                      <div className="flex justify-between items-start">
                        <span className="text-slate-700">{reason.fact}</span>
                        <div className="text-xs text-slate-500">
                          <span className="font-semibold">Weight: {reason.weight}</span>
                          <span className="ml-2">Confidence: {(reason.confidence * 100).toFixed(0)}%</span>
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
             </div>
          )}
      </div>
      
      {/* QR Code for Follow up - Print Only */}
      <div className="hidden print:block mt-8 pt-8 border-t">
         <div className="flex items-center justify-between">
             <div>
                 <h3 className="font-bold text-lg">Follow Up</h3>
                 <p className="text-sm text-gray-600">Scan to schedule appointment</p>
             </div>
             <div className="border-2 border-black p-2">
                <QrCode className="w-16 h-16" />
             </div>
         </div>
      </div>

      {/* Floating Action Bar */}
      <div className="fixed bottom-0 left-0 right-0 bg-white border-t p-4 shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1)] z-10 print:hidden">
        <div className="max-w-4xl mx-auto flex gap-3">
            <button 
                onClick={onReset}
                className="flex-1 py-3 rounded-xl border-2 border-gray-300 text-gray-700 font-bold hover:bg-gray-50 transition-colors"
            >
                New Assessment
            </button>
             <button 
                className="flex-[1.5] py-3 rounded-xl bg-blue-700 text-white font-bold hover:bg-blue-800 transition-colors shadow-md flex items-center justify-center gap-2"
                onClick={handlePrint}
            >
                <Printer className="w-5 h-5" />
                Download PDF / Print
            </button>
        </div>
      </div>

    </div>
  );
};

// Simple icon component
const StethoscopeIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-600">
    <path d="M4.8 2.3A.3.3 0 0 0 5 2.5h3.2c.2 0 .4-.1.4-.3v-.1a.3.3 0 0 0-.3-.3H5a.3.3 0 0 0-.3.3v.1zM6 5v6a4 4 0 0 0 4 4h4a4 4 0 0 0 4-4V5"/><circle cx="12" cy="19" r="2"/><path d="M8 2v3"/><path d="M16 2v3"/>
  </svg>
);

export default ResultView;